/**
 * EntityQrCode — compact QR identity card for Entity Detail Workspace headers.
 * Payload / export pipelines reuse identification helpers.
 */

import { Download, Loader2, Maximize2, Printer } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";

import { PermissionGate } from "@/components/PermissionGate";
import {
  downloadIdentificationQrPng,
  printIdentificationLabel,
  type IdentificationLabelContext,
  type IdentificationLabelMetadataRow,
  useIdentificationQr,
} from "@/components/identification";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import {
  Toast,
  ToastAction,
  ToastClose,
  ToastDescription,
  ToastProvider,
  ToastTitle,
  ToastViewport,
} from "@/components/ui/toast";
import { isExportCancelled, revealInFolder } from "@/export";
import { useToast } from "@/hooks/use-toast";
import { getActivationLicenseMetadata } from "@/services/product-license-service";
import { toErrorMessage } from "@/utils/errors";

export interface EntityQrCodeProps {
  code: string;
  name: string;
  /** Deep-link payload, e.g. maintafox://article/12 */
  payload: string;
  viewPermission: string;
  metadata?: IdentificationLabelMetadataRow[];
  dialogTitle?: string;
  scanHint?: string;
  labels?: {
    scanId?: string;
    expand?: string;
    printLabel?: string;
    downloadPng?: string;
    openFolder?: string;
    exportSavedTitle?: string;
    exportFailedTitle?: string;
    printStartedTitle?: string;
    printStartedDescription?: string;
  };
}

const COMPACT_SIZE_PX = 90;
const EXPANDED_SIZE_PX = 180;

function QrSvg({
  svgHtml,
  loading,
  error,
  size,
}: {
  svgHtml: string;
  loading: boolean;
  error: string | null;
  size: number;
}) {
  return (
    <div
      className="flex items-center justify-center rounded-sm bg-white p-1"
      style={{ width: size, height: size }}
    >
      {loading ? (
        <Loader2 className="h-6 w-6 animate-spin text-text-muted" aria-hidden />
      ) : error ? (
        <span className="px-1 text-center text-[10px] text-status-danger">{error}</span>
      ) : (
        <div
          className="h-full w-full [&>svg]:h-full [&>svg]:w-full"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG generated by qrcode lib
          dangerouslySetInnerHTML={{ __html: svgHtml }}
        />
      )}
    </div>
  );
}

export function EntityQrCode({
  code,
  name,
  payload,
  viewPermission,
  metadata = [],
  dialogTitle,
  scanHint,
  labels = {},
}: EntityQrCodeProps) {
  const { t } = useTranslation("common");
  const { toasts, toast, dismiss } = useToast();
  const [open, setOpen] = useState(false);
  const [companyName, setCompanyName] = useState<string | null>(null);
  const [exportBusy, setExportBusy] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);

  const L = {
    scanId: labels.scanId ?? t("detailWorkspace.qr.scanId"),
    expand: labels.expand ?? t("detailWorkspace.qr.expand"),
    printLabel: labels.printLabel ?? t("detailWorkspace.qr.printLabel"),
    downloadPng: labels.downloadPng ?? t("detailWorkspace.qr.downloadPng"),
    openFolder: labels.openFolder ?? t("detailWorkspace.qr.openFolder"),
    exportSavedTitle: labels.exportSavedTitle ?? t("detailWorkspace.qr.exportSavedTitle"),
    exportFailedTitle: labels.exportFailedTitle ?? t("detailWorkspace.qr.exportFailedTitle"),
    printStartedTitle: labels.printStartedTitle ?? t("detailWorkspace.qr.printStartedTitle"),
    printStartedDescription:
      labels.printStartedDescription ?? t("detailWorkspace.qr.printStartedDescription"),
  };

  useEffect(() => {
    let cancelled = false;
    void getActivationLicenseMetadata()
      .then((meta) => {
        if (cancelled) return;
        setCompanyName(meta?.company_display_name?.trim() || null);
      })
      .catch(() => {
        if (!cancelled) setCompanyName(null);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    setOpen(false);
    setExportError(null);
  }, [payload]);

  const context = useMemo<IdentificationLabelContext>(
    () => ({
      dialogTitle: dialogTitle ?? L.scanId,
      description: scanHint ?? "",
      primaryCode: code,
      name,
      metadata,
      payload,
      filenameStem: code,
    }),
    [code, dialogTitle, L.scanId, metadata, name, payload, scanHint],
  );

  const { svgHtml, loading, error } = useIdentificationQr(context.payload, true);
  const canExport = !loading && !error && Boolean(svgHtml);

  const handleDownload = useCallback(async () => {
    setExportError(null);
    setExportBusy(true);
    try {
      const result = await downloadIdentificationQrPng(context, companyName);
      if (result.status === "saved") {
        toast({
          title: L.exportSavedTitle,
          description: result.path,
          variant: "success",
        });
      }
    } catch (err) {
      if (isExportCancelled(err)) return;
      const msg = toErrorMessage(err);
      setExportError(msg);
      toast({ title: L.exportFailedTitle, description: msg, variant: "destructive" });
    } finally {
      setExportBusy(false);
    }
  }, [companyName, context, L.exportFailedTitle, L.exportSavedTitle, toast]);

  const handlePrint = useCallback(async () => {
    if (!svgHtml) return;
    setExportError(null);
    setExportBusy(true);
    try {
      await printIdentificationLabel({
        context,
        svgHtml,
        companyName: companyName ?? null,
      });
      toast({
        title: L.printStartedTitle,
        description: L.printStartedDescription,
        variant: "default",
      });
    } catch (err) {
      const msg = toErrorMessage(err);
      setExportError(msg);
      toast({ title: L.exportFailedTitle, description: msg, variant: "destructive" });
    } finally {
      setExportBusy(false);
    }
  }, [
    companyName,
    context,
    L.exportFailedTitle,
    L.printStartedDescription,
    L.printStartedTitle,
    svgHtml,
    toast,
  ]);

  const handleOpenFolder = useCallback(
    async (path: string) => {
      try {
        await revealInFolder(path);
      } catch (err) {
        toast({
          title: L.exportFailedTitle,
          description: toErrorMessage(err),
          variant: "destructive",
        });
      }
    },
    [L.exportFailedTitle, toast],
  );

  return (
    <PermissionGate permission={viewPermission}>
      <ToastProvider>
        <Popover open={open} onOpenChange={setOpen}>
          <div className="relative flex w-[124px] flex-col items-center gap-1.5 rounded-md border border-surface-border bg-surface-1 p-2.5 shadow-sm">
            <PopoverTrigger asChild>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="absolute right-0.5 top-0.5 h-7 w-7 text-text-muted"
                aria-label={L.expand}
              >
                <Maximize2 className="h-3.5 w-3.5" />
              </Button>
            </PopoverTrigger>

            <p className="pr-6 text-[10px] font-medium uppercase tracking-wide text-text-muted">
              {L.scanId}
            </p>

            <button
              type="button"
              className="rounded-sm outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"
              aria-label={L.expand}
              onClick={() => setOpen(true)}
            >
              <QrSvg
                svgHtml={svgHtml}
                loading={loading}
                error={error}
                size={COMPACT_SIZE_PX}
              />
            </button>

            <p className="max-w-full truncate font-mono text-xs text-text-primary">{code}</p>
          </div>

          <PopoverContent
            align="end"
            side="bottom"
            className="flex w-[240px] flex-col items-center gap-3"
          >
            <p className="text-[10px] font-medium uppercase tracking-wide text-text-muted">
              {L.scanId}
            </p>
            <QrSvg
              svgHtml={svgHtml}
              loading={loading}
              error={error}
              size={EXPANDED_SIZE_PX}
            />
            <p className="font-mono text-xs text-text-primary">{code}</p>
            {exportError ? (
              <p className="text-center text-xs text-status-danger" role="alert">
                {exportError}
              </p>
            ) : null}
            <div className="flex w-full flex-wrap justify-center gap-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={!canExport || exportBusy}
                onClick={() => void handlePrint()}
              >
                <Printer className="mr-1.5 h-3.5 w-3.5" />
                {L.printLabel}
              </Button>
              <Button
                type="button"
                size="sm"
                disabled={!canExport || exportBusy}
                onClick={() => void handleDownload()}
              >
                {exportBusy ? (
                  <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Download className="mr-1.5 h-3.5 w-3.5" />
                )}
                {L.downloadPng}
              </Button>
            </div>
          </PopoverContent>
        </Popover>

        {toasts.map((tm) => {
          const path = tm.variant === "success" && tm.description ? tm.description : null;
          return (
            <Toast
              key={tm.id}
              {...(tm.variant ? { variant: tm.variant } : {})}
              open
              onOpenChange={(isOpen) => {
                if (!isOpen) dismiss(tm.id);
              }}
            >
              <div className="grid gap-1">
                <ToastTitle>{tm.title}</ToastTitle>
                {tm.description ? (
                  <ToastDescription className="break-all font-mono text-[11px]">
                    {tm.description}
                  </ToastDescription>
                ) : null}
              </div>
              {path ? (
                <ToastAction asChild altText={L.openFolder}>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => void handleOpenFolder(path)}
                  >
                    {L.openFolder}
                  </Button>
                </ToastAction>
              ) : null}
              <ToastClose />
            </Toast>
          );
        })}
        <ToastViewport />
      </ToastProvider>
    </PermissionGate>
  );
}
