// @generated by scripts/generate-permissions.ts — DO NOT EDIT
// Source: shared/rbac/permission-registry.json

#![allow(dead_code)]

//! Generated canonical permission constants and catalog metadata.

/// One row from the canonical permission registry.
#[derive(Debug, Clone, Copy)]
pub struct PermissionMeta {
    pub name: &'static str,
    pub description: &'static str,
    pub category: &'static str,
    pub is_dangerous: bool,
    pub requires_step_up: bool,
    pub usage: &'static str,
    pub aliases: &'static [&'static str],
}

/// Dependency edge from the canonical registry.
#[derive(Debug, Clone, Copy)]
pub struct PermissionDep {
    pub permission: &'static str,
    pub requires: &'static str,
    pub dep_type: &'static str,
}

/// View equipment registry
pub const EQ_VIEW: &str = "eq.view";
/// Create and edit equipment records
pub const EQ_MANAGE: &str = "eq.manage";
/// Import equipment from CSV / ERP
pub const EQ_IMPORT: &str = "eq.import";
/// Soft-delete equipment records
pub const EQ_DELETE: &str = "eq.delete";
/// View intervention request list and details
pub const DI_VIEW: &str = "di.view";
/// Submit new intervention requests (all assets)
pub const DI_CREATE: &str = "di.create";
/// Submit intervention requests (own entity only)
pub const DI_CREATE_OWN: &str = "di.create.own";
/// Triage incoming DIs (submitted to review queue)
pub const DI_SCREEN: &str = "di.screen";
/// Screen, return, and reject intervention requests
pub const DI_REVIEW: &str = "di.review";
/// Approve, defer, or reactivate intervention requests
pub const DI_APPROVE: &str = "di.approve";
/// Convert approved DI to work order
pub const DI_CONVERT: &str = "di.convert";
/// Override, archive, reopen, manage DI settings
pub const DI_ADMIN: &str = "di.admin";
/// Delete draft intervention requests
pub const DI_DELETE: &str = "di.delete";
/// View work orders and details
pub const OT_VIEW: &str = "ot.view";
/// Create new work orders
pub const OT_CREATE: &str = "ot.create";
/// Edit, plan, assign, and execute work orders
pub const OT_EDIT: &str = "ot.edit";
/// Approve work orders from draft / planning
pub const OT_APPROVE: &str = "ot.approve";
/// Close technically verified work orders
pub const OT_CLOSE: &str = "ot.close";
/// Reopen recently closed work orders
pub const OT_REOPEN: &str = "ot.reopen";
/// Override, archive, manage WO settings
pub const OT_ADMIN: &str = "ot.admin";
/// Delete draft work orders
pub const OT_DELETE: &str = "ot.delete";
/// View organizational structure
pub const ORG_VIEW: &str = "org.view";
/// Create and edit org nodes and entities
pub const ORG_MANAGE: &str = "org.manage";
/// Publish, archive, and merge org units
pub const ORG_ADMIN: &str = "org.admin";
/// View personnel records
pub const PER_VIEW: &str = "per.view";
/// Create and edit personnel records
pub const PER_MANAGE: &str = "per.manage";
/// View and export workforce reports
pub const PER_REPORT: &str = "per.report";
/// View sensitive personnel fields
pub const PER_SENSITIVEVIEW: &str = "per.sensitiveview";
/// View reference and lookup values
pub const REF_VIEW: &str = "ref.view";
/// Create and edit governed reference values
pub const REF_MANAGE: &str = "ref.manage";
/// Publish reference domain versions
pub const REF_PUBLISH: &str = "ref.publish";
/// View inventory and stock levels
pub const INV_VIEW: &str = "inv.view";
/// Issue, return, adjust, and transfer stock
pub const INV_MANAGE: &str = "inv.manage";
/// Create and approve purchase requisitions and orders
pub const INV_PROCURE: &str = "inv.procure";
/// Execute and post stock count sessions
pub const INV_COUNT: &str = "inv.count";
/// View PM plans and occurrences
pub const PM_VIEW: &str = "pm.view";
/// Create new PM plans
pub const PM_CREATE: &str = "pm.create";
/// Edit PM plans and versions
pub const PM_EDIT: &str = "pm.edit";
/// Delete draft PM plans
pub const PM_DELETE: &str = "pm.delete";
/// Approve PM plan changes
pub const PM_APPROVE: &str = "pm.approve";
/// View RAMS and reliability data
pub const RAM_VIEW: &str = "ram.view";
/// Edit RAMS records and failure modes
pub const RAM_MANAGE: &str = "ram.manage";
/// Run advanced RAMS analysis
pub const RAM_ANALYZE: &str = "ram.analyze";
/// Export RAMS analysis artifacts
pub const RAM_EXPORT: &str = "ram.export";
/// View standard reports and analytics
pub const REP_VIEW: &str = "rep.view";
/// Export report data
pub const REP_EXPORT: &str = "rep.export";
/// Create and edit custom reports
pub const REP_MANAGE: &str = "rep.manage";
/// Browse archive entries
pub const ARC_VIEW: &str = "arc.view";
/// Restore archived records
pub const ARC_RESTORE: &str = "arc.restore";
/// Export archived data
pub const ARC_EXPORT: &str = "arc.export";
/// Permanently purge archived records
pub const ARC_PURGE: &str = "arc.purge";
/// View documentation and library content
pub const DOC_VIEW: &str = "doc.view";
/// Create and edit documentation articles
pub const DOC_MANAGE: &str = "doc.manage";
/// View planning and scheduling data
pub const PLAN_VIEW: &str = "plan.view";
/// Edit planning schedules and commitments
pub const PLAN_EDIT: &str = "plan.edit";
/// Confirm planning commitments
pub const PLAN_CONFIRM: &str = "plan.confirm";
/// Manage planning windows
pub const PLAN_WINDOWS: &str = "plan.windows";
/// View activity feed and scoped audit events
pub const LOG_VIEW: &str = "log.view";
/// Export audit log data
pub const LOG_EXPORT: &str = "log.export";
/// Administer audit log retention and policy
pub const LOG_ADMIN: &str = "log.admin";
/// View training and certification records
pub const TRN_VIEW: &str = "trn.view";
/// Manage training records and plans
pub const TRN_MANAGE: &str = "trn.manage";
/// Issue or revoke certifications
pub const TRN_CERTIFY: &str = "trn.certify";
/// View IoT device data and readings
pub const IOT_VIEW: &str = "iot.view";
/// Configure IoT gateways and devices
pub const IOT_MANAGE: &str = "iot.manage";
/// View ERP sync status and mappings
pub const ERP_VIEW: &str = "erp.view";
/// Configure ERP integration settings
pub const ERP_CONFIGURE: &str = "erp.configure";
/// Reconcile ERP posting states for goods receipts
pub const ERP_RECONCILE: &str = "erp.reconcile";
/// View work permits
pub const PTW_VIEW: &str = "ptw.view";
/// Issue work permits
pub const PTW_ISSUE: &str = "ptw.issue";
/// Close and cancel work permits
pub const PTW_CLOSE: &str = "ptw.close";
/// View budgets and cost data
pub const FIN_VIEW: &str = "fin.view";
/// Manage governed budget baselines
pub const FIN_BUDGET: &str = "fin.budget";
/// Export governed budget reports
pub const FIN_REPORT: &str = "fin.report";
/// Manage budgets and cost centers (legacy umbrella)
pub const FIN_MANAGE: &str = "fin.manage";
/// Post cost actuals to ERP
pub const FIN_POST: &str = "fin.post";
/// Approve cost events and commitments
pub const FIN_APPROVE: &str = "fin.approve";
/// View inspection rounds and checklists
pub const INS_VIEW: &str = "ins.view";
/// Execute inspection rounds and record results
pub const INS_EXECUTE: &str = "ins.execute";
/// Manage inspection templates and schedules
pub const INS_ADMIN: &str = "ins.admin";
/// View tenant configuration
pub const CFG_VIEW: &str = "cfg.view";
/// Manage tenant configuration rules
pub const CFG_MANAGE: &str = "cfg.manage";
/// Publish configuration changes globally
pub const CFG_PUBLISH: &str = "cfg.publish";
/// Manage user accounts and scope assignments
pub const ADM_USERS: &str = "adm.users";
/// Manage roles and role permissions
pub const ADM_ROLES: &str = "adm.roles";
/// View and govern the permission catalog
pub const ADM_PERMISSIONS: &str = "adm.permissions";
/// Manage application settings and diagnostics
pub const ADM_SETTINGS: &str = "adm.settings";
/// View the full audit log
pub const ADM_AUDIT: &str = "adm.audit";
/// View sync health, conflicts, and replay history
pub const SYNC_VIEW: &str = "sync.view";
/// Apply sync batches and stage sync envelopes
pub const SYNC_MANAGE: &str = "sync.manage";
/// Resolve sync conflicts
pub const SYNC_RESOLVE: &str = "sync.resolve";
/// Run sync replay and checkpoint rollback workflows
pub const SYNC_REPLAY: &str = "sync.replay";
/// Preview and execute scoped sync repair actions
pub const SYNC_REPAIR: &str = "sync.repair";
/// Repair data integrity findings
pub const INTEGRITY_REPAIR: &str = "integrity.repair";
/// View machine activation state
pub const ACT_VIEW: &str = "act.view";
/// Manage machine activation
pub const ACT_MANAGE: &str = "act.manage";
/// View license enforcement state
pub const LIC_VIEW: &str = "lic.view";
/// Manage license enforcement matrix
pub const LIC_MANAGE: &str = "lic.manage";
/// View entitlement envelopes
pub const ENT_VIEW: &str = "ent.view";
/// Manage entitlement envelopes
pub const ENT_MANAGE: &str = "ent.manage";
/// Access vendor control-plane console shell
pub const CONSOLE_VIEW: &str = "console.view";
/// Manage tenant customer records in vendor console
pub const CUSTOMER_MANAGE: &str = "customer.manage";
/// Change entitlements and license posture in vendor console
pub const ENTITLEMENT_MANAGE: &str = "entitlement.manage";
/// Vendor-console sync operations
pub const SYNC_OPERATE: &str = "sync.operate";
/// Publish and roll back control-plane update rollouts
pub const ROLLOUT_MANAGE: &str = "rollout.manage";
/// View platform health and integration status
pub const PLATFORM_OBSERVE: &str = "platform.observe";
/// Read vendor-scoped audit and evidence trails
pub const AUDIT_VIEW: &str = "audit.view";

/// Full canonical catalog (system permissions).
pub const CATALOG: &[PermissionMeta] = &[
    PermissionMeta {
        name: EQ_VIEW,
        description: "View equipment registry",
        category: "eq",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: EQ_MANAGE,
        description: "Create and edit equipment records",
        category: "eq",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["eq.create", "eq.edit", "eq.admin"],
    },
    PermissionMeta {
        name: EQ_IMPORT,
        description: "Import equipment from CSV / ERP",
        category: "eq",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: EQ_DELETE,
        description: "Soft-delete equipment records",
        category: "eq",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: DI_VIEW,
        description: "View intervention request list and details",
        category: "di",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: DI_CREATE,
        description: "Submit new intervention requests (all assets)",
        category: "di",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["di.submit"],
    },
    PermissionMeta {
        name: DI_CREATE_OWN,
        description: "Submit intervention requests (own entity only)",
        category: "di",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["di.submit.own"],
    },
    PermissionMeta {
        name: DI_SCREEN,
        description: "Triage incoming DIs (submitted to review queue)",
        category: "di",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: DI_REVIEW,
        description: "Screen, return, and reject intervention requests",
        category: "di",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: DI_APPROVE,
        description: "Approve, defer, or reactivate intervention requests",
        category: "di",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: DI_CONVERT,
        description: "Convert approved DI to work order",
        category: "di",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: DI_ADMIN,
        description: "Override, archive, reopen, manage DI settings",
        category: "di",
        is_dangerous: true,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: DI_DELETE,
        description: "Delete draft intervention requests",
        category: "di",
        is_dangerous: true,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: OT_VIEW,
        description: "View work orders and details",
        category: "ot",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: OT_CREATE,
        description: "Create new work orders",
        category: "ot",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: OT_EDIT,
        description: "Edit, plan, assign, and execute work orders",
        category: "ot",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: OT_APPROVE,
        description: "Approve work orders from draft / planning",
        category: "ot",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: OT_CLOSE,
        description: "Close technically verified work orders",
        category: "ot",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: OT_REOPEN,
        description: "Reopen recently closed work orders",
        category: "ot",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: OT_ADMIN,
        description: "Override, archive, manage WO settings",
        category: "ot",
        is_dangerous: true,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: OT_DELETE,
        description: "Delete draft work orders",
        category: "ot",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: ORG_VIEW,
        description: "View organizational structure",
        category: "org",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ORG_MANAGE,
        description: "Create and edit org nodes and entities",
        category: "org",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["org.edit"],
    },
    PermissionMeta {
        name: ORG_ADMIN,
        description: "Publish, archive, and merge org units",
        category: "org",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PER_VIEW,
        description: "View personnel records",
        category: "per",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PER_MANAGE,
        description: "Create and edit personnel records",
        category: "per",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["per.create", "per.edit", "per.delete", "per.admin"],
    },
    PermissionMeta {
        name: PER_REPORT,
        description: "View and export workforce reports",
        category: "per",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PER_SENSITIVEVIEW,
        description: "View sensitive personnel fields",
        category: "per",
        is_dangerous: false,
        requires_step_up: false,
        usage: "catalog-only",
        aliases: &[],
    },
    PermissionMeta {
        name: REF_VIEW,
        description: "View reference and lookup values",
        category: "ref",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: REF_MANAGE,
        description: "Create and edit governed reference values",
        category: "ref",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["ref.edit", "ref.admin"],
    },
    PermissionMeta {
        name: REF_PUBLISH,
        description: "Publish reference domain versions",
        category: "ref",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: INV_VIEW,
        description: "View inventory and stock levels",
        category: "inv",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: INV_MANAGE,
        description: "Issue, return, adjust, and transfer stock",
        category: "inv",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: INV_PROCURE,
        description: "Create and approve purchase requisitions and orders",
        category: "inv",
        is_dangerous: true,
        requires_step_up: false,
        usage: "both",
        aliases: &["inv.order"],
    },
    PermissionMeta {
        name: INV_COUNT,
        description: "Execute and post stock count sessions",
        category: "inv",
        is_dangerous: true,
        requires_step_up: false,
        usage: "both",
        aliases: &["inv.adjust"],
    },
    PermissionMeta {
        name: PM_VIEW,
        description: "View PM plans and occurrences",
        category: "pm",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PM_CREATE,
        description: "Create new PM plans",
        category: "pm",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PM_EDIT,
        description: "Edit PM plans and versions",
        category: "pm",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["pm.manage"],
    },
    PermissionMeta {
        name: PM_DELETE,
        description: "Delete draft PM plans",
        category: "pm",
        is_dangerous: true,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PM_APPROVE,
        description: "Approve PM plan changes",
        category: "pm",
        is_dangerous: false,
        requires_step_up: false,
        usage: "catalog-only",
        aliases: &[],
    },
    PermissionMeta {
        name: RAM_VIEW,
        description: "View RAMS and reliability data",
        category: "ram",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: RAM_MANAGE,
        description: "Edit RAMS records and failure modes",
        category: "ram",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: RAM_ANALYZE,
        description: "Run advanced RAMS analysis",
        category: "ram",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: RAM_EXPORT,
        description: "Export RAMS analysis artifacts",
        category: "ram",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: REP_VIEW,
        description: "View standard reports and analytics",
        category: "rep",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: REP_EXPORT,
        description: "Export report data",
        category: "rep",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: REP_MANAGE,
        description: "Create and edit custom reports",
        category: "rep",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["rep.admin"],
    },
    PermissionMeta {
        name: ARC_VIEW,
        description: "Browse archive entries",
        category: "arc",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ARC_RESTORE,
        description: "Restore archived records",
        category: "arc",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ARC_EXPORT,
        description: "Export archived data",
        category: "arc",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ARC_PURGE,
        description: "Permanently purge archived records",
        category: "arc",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: DOC_VIEW,
        description: "View documentation and library content",
        category: "doc",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: DOC_MANAGE,
        description: "Create and edit documentation articles",
        category: "doc",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["doc.author", "doc.admin"],
    },
    PermissionMeta {
        name: PLAN_VIEW,
        description: "View planning and scheduling data",
        category: "plan",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PLAN_EDIT,
        description: "Edit planning schedules and commitments",
        category: "plan",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &["plan.manage", "plan.admin"],
    },
    PermissionMeta {
        name: PLAN_CONFIRM,
        description: "Confirm planning commitments",
        category: "plan",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PLAN_WINDOWS,
        description: "Manage planning windows",
        category: "plan",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: LOG_VIEW,
        description: "View activity feed and scoped audit events",
        category: "log",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: LOG_EXPORT,
        description: "Export audit log data",
        category: "log",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: LOG_ADMIN,
        description: "Administer audit log retention and policy",
        category: "log",
        is_dangerous: true,
        requires_step_up: true,
        usage: "catalog-only",
        aliases: &[],
    },
    PermissionMeta {
        name: TRN_VIEW,
        description: "View training and certification records",
        category: "trn",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: TRN_MANAGE,
        description: "Manage training records and plans",
        category: "trn",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: TRN_CERTIFY,
        description: "Issue or revoke certifications",
        category: "trn",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &["trn.override"],
    },
    PermissionMeta {
        name: IOT_VIEW,
        description: "View IoT device data and readings",
        category: "iot",
        is_dangerous: false,
        requires_step_up: false,
        usage: "catalog-only",
        aliases: &[],
    },
    PermissionMeta {
        name: IOT_MANAGE,
        description: "Configure IoT gateways and devices",
        category: "iot",
        is_dangerous: false,
        requires_step_up: false,
        usage: "catalog-only",
        aliases: &["iot.configure"],
    },
    PermissionMeta {
        name: ERP_VIEW,
        description: "View ERP sync status and mappings",
        category: "erp",
        is_dangerous: false,
        requires_step_up: false,
        usage: "catalog-only",
        aliases: &[],
    },
    PermissionMeta {
        name: ERP_CONFIGURE,
        description: "Configure ERP integration settings",
        category: "erp",
        is_dangerous: true,
        requires_step_up: true,
        usage: "catalog-only",
        aliases: &["erp.manage"],
    },
    PermissionMeta {
        name: ERP_RECONCILE,
        description: "Reconcile ERP posting states for goods receipts",
        category: "erp",
        is_dangerous: true,
        requires_step_up: false,
        usage: "both",
        aliases: &["erp.sync"],
    },
    PermissionMeta {
        name: PTW_VIEW,
        description: "View work permits",
        category: "ptw",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PTW_ISSUE,
        description: "Issue work permits",
        category: "ptw",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &["ptw.create", "ptw.approve"],
    },
    PermissionMeta {
        name: PTW_CLOSE,
        description: "Close and cancel work permits",
        category: "ptw",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &["ptw.cancel"],
    },
    PermissionMeta {
        name: FIN_VIEW,
        description: "View budgets and cost data",
        category: "fin",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: FIN_BUDGET,
        description: "Manage governed budget baselines",
        category: "fin",
        is_dangerous: true,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: FIN_REPORT,
        description: "Export governed budget reports",
        category: "fin",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: FIN_MANAGE,
        description: "Manage budgets and cost centers (legacy umbrella)",
        category: "fin",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: FIN_POST,
        description: "Post cost actuals to ERP",
        category: "fin",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: FIN_APPROVE,
        description: "Approve cost events and commitments",
        category: "fin",
        is_dangerous: true,
        requires_step_up: true,
        usage: "catalog-only",
        aliases: &[],
    },
    PermissionMeta {
        name: INS_VIEW,
        description: "View inspection rounds and checklists",
        category: "ins",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: INS_EXECUTE,
        description: "Execute inspection rounds and record results",
        category: "ins",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &["ins.complete"],
    },
    PermissionMeta {
        name: INS_ADMIN,
        description: "Manage inspection templates and schedules",
        category: "ins",
        is_dangerous: true,
        requires_step_up: false,
        usage: "backend",
        aliases: &["ins.manage"],
    },
    PermissionMeta {
        name: CFG_VIEW,
        description: "View tenant configuration",
        category: "cfg",
        is_dangerous: false,
        requires_step_up: false,
        usage: "frontend",
        aliases: &[],
    },
    PermissionMeta {
        name: CFG_MANAGE,
        description: "Manage tenant configuration rules",
        category: "cfg",
        is_dangerous: true,
        requires_step_up: true,
        usage: "catalog-only",
        aliases: &["cfg.edit", "cfg.admin"],
    },
    PermissionMeta {
        name: CFG_PUBLISH,
        description: "Publish configuration changes globally",
        category: "cfg",
        is_dangerous: true,
        requires_step_up: true,
        usage: "catalog-only",
        aliases: &[],
    },
    PermissionMeta {
        name: ADM_USERS,
        description: "Manage user accounts and scope assignments",
        category: "adm",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ADM_ROLES,
        description: "Manage roles and role permissions",
        category: "adm",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ADM_PERMISSIONS,
        description: "View and govern the permission catalog",
        category: "adm",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ADM_SETTINGS,
        description: "Manage application settings and diagnostics",
        category: "adm",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ADM_AUDIT,
        description: "View the full audit log",
        category: "adm",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: SYNC_VIEW,
        description: "View sync health, conflicts, and replay history",
        category: "sync",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: SYNC_MANAGE,
        description: "Apply sync batches and stage sync envelopes",
        category: "sync",
        is_dangerous: true,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: SYNC_RESOLVE,
        description: "Resolve sync conflicts",
        category: "sync",
        is_dangerous: true,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: SYNC_REPLAY,
        description: "Run sync replay and checkpoint rollback workflows",
        category: "sync",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: SYNC_REPAIR,
        description: "Preview and execute scoped sync repair actions",
        category: "sync",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: INTEGRITY_REPAIR,
        description: "Repair data integrity findings",
        category: "integrity",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ACT_VIEW,
        description: "View machine activation state",
        category: "act",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: ACT_MANAGE,
        description: "Manage machine activation",
        category: "act",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: LIC_VIEW,
        description: "View license enforcement state",
        category: "lic",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: LIC_MANAGE,
        description: "Manage license enforcement matrix",
        category: "lic",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: ENT_VIEW,
        description: "View entitlement envelopes",
        category: "ent",
        is_dangerous: false,
        requires_step_up: false,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: ENT_MANAGE,
        description: "Manage entitlement envelopes",
        category: "ent",
        is_dangerous: true,
        requires_step_up: true,
        usage: "backend",
        aliases: &[],
    },
    PermissionMeta {
        name: CONSOLE_VIEW,
        description: "Access vendor control-plane console shell",
        category: "vendor_console",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: CUSTOMER_MANAGE,
        description: "Manage tenant customer records in vendor console",
        category: "vendor_console",
        is_dangerous: true,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ENTITLEMENT_MANAGE,
        description: "Change entitlements and license posture in vendor console",
        category: "vendor_console",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: SYNC_OPERATE,
        description: "Vendor-console sync operations",
        category: "vendor_console",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: ROLLOUT_MANAGE,
        description: "Publish and roll back control-plane update rollouts",
        category: "vendor_console",
        is_dangerous: true,
        requires_step_up: true,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: PLATFORM_OBSERVE,
        description: "View platform health and integration status",
        category: "vendor_console",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
    PermissionMeta {
        name: AUDIT_VIEW,
        description: "Read vendor-scoped audit and evidence trails",
        category: "vendor_console",
        is_dangerous: false,
        requires_step_up: false,
        usage: "both",
        aliases: &[],
    },
];

/// Canonical permission dependencies.
pub const DEPENDENCIES: &[PermissionDep] = &[
    PermissionDep {
        permission: OT_CREATE,
        requires: OT_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: OT_EDIT,
        requires: OT_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: OT_APPROVE,
        requires: OT_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: OT_CLOSE,
        requires: OT_EDIT,
        dep_type: "hard",
    },
    PermissionDep {
        permission: OT_REOPEN,
        requires: OT_CLOSE,
        dep_type: "warn",
    },
    PermissionDep {
        permission: DI_CREATE,
        requires: DI_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: DI_CREATE_OWN,
        requires: DI_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: DI_SCREEN,
        requires: DI_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: DI_REVIEW,
        requires: DI_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: DI_APPROVE,
        requires: DI_REVIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: DI_CONVERT,
        requires: DI_APPROVE,
        dep_type: "hard",
    },
    PermissionDep {
        permission: EQ_MANAGE,
        requires: EQ_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: EQ_DELETE,
        requires: EQ_MANAGE,
        dep_type: "warn",
    },
    PermissionDep {
        permission: EQ_IMPORT,
        requires: EQ_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: PM_CREATE,
        requires: PM_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: PM_EDIT,
        requires: PM_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: PM_DELETE,
        requires: PM_EDIT,
        dep_type: "warn",
    },
    PermissionDep {
        permission: INV_MANAGE,
        requires: INV_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: INV_PROCURE,
        requires: INV_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: INV_COUNT,
        requires: INV_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ORG_MANAGE,
        requires: ORG_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ORG_ADMIN,
        requires: ORG_MANAGE,
        dep_type: "warn",
    },
    PermissionDep {
        permission: PER_MANAGE,
        requires: PER_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: PER_REPORT,
        requires: PER_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: REF_MANAGE,
        requires: REF_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: REF_PUBLISH,
        requires: REF_MANAGE,
        dep_type: "warn",
    },
    PermissionDep {
        permission: PLAN_EDIT,
        requires: PLAN_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: PLAN_CONFIRM,
        requires: PLAN_EDIT,
        dep_type: "hard",
    },
    PermissionDep {
        permission: PLAN_WINDOWS,
        requires: PLAN_EDIT,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ADM_ROLES,
        requires: ADM_USERS,
        dep_type: "warn",
    },
    PermissionDep {
        permission: ADM_PERMISSIONS,
        requires: ADM_ROLES,
        dep_type: "hard",
    },
    PermissionDep {
        permission: SYNC_MANAGE,
        requires: SYNC_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: SYNC_RESOLVE,
        requires: SYNC_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: SYNC_REPLAY,
        requires: SYNC_RESOLVE,
        dep_type: "hard",
    },
    PermissionDep {
        permission: SYNC_REPAIR,
        requires: SYNC_REPLAY,
        dep_type: "hard",
    },
    PermissionDep {
        permission: INTEGRITY_REPAIR,
        requires: SYNC_MANAGE,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ENT_MANAGE,
        requires: ENT_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ACT_MANAGE,
        requires: ACT_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: LIC_MANAGE,
        requires: LIC_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: LOG_EXPORT,
        requires: LOG_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ARC_RESTORE,
        requires: ARC_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ARC_EXPORT,
        requires: ARC_VIEW,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ARC_PURGE,
        requires: ARC_RESTORE,
        dep_type: "hard",
    },
    PermissionDep {
        permission: ADM_AUDIT,
        requires: LOG_VIEW,
        dep_type: "warn",
    },
];

/// Alias → canonical name pairs for grant migration.
pub const ALIAS_MAP: &[(&str, &str)] = &[
    ("eq.create", EQ_MANAGE),
    ("eq.edit", EQ_MANAGE),
    ("eq.admin", EQ_MANAGE),
    ("di.submit", DI_CREATE),
    ("di.submit.own", DI_CREATE_OWN),
    ("org.edit", ORG_MANAGE),
    ("per.create", PER_MANAGE),
    ("per.edit", PER_MANAGE),
    ("per.delete", PER_MANAGE),
    ("per.admin", PER_MANAGE),
    ("ref.edit", REF_MANAGE),
    ("ref.admin", REF_MANAGE),
    ("inv.order", INV_PROCURE),
    ("inv.adjust", INV_COUNT),
    ("pm.manage", PM_EDIT),
    ("rep.admin", REP_MANAGE),
    ("doc.author", DOC_MANAGE),
    ("doc.admin", DOC_MANAGE),
    ("plan.manage", PLAN_EDIT),
    ("plan.admin", PLAN_EDIT),
    ("trn.override", TRN_CERTIFY),
    ("iot.configure", IOT_MANAGE),
    ("erp.manage", ERP_CONFIGURE),
    ("erp.sync", ERP_RECONCILE),
    ("ptw.create", PTW_ISSUE),
    ("ptw.approve", PTW_ISSUE),
    ("ptw.cancel", PTW_CLOSE),
    ("ins.complete", INS_EXECUTE),
    ("ins.manage", INS_ADMIN),
    ("cfg.edit", CFG_MANAGE),
    ("cfg.admin", CFG_MANAGE),
];

/// Permissions excluded from Supervisor / Maintenance Supervisor defaults.
pub const SUPERVISOR_EXCLUSIONS: &[&str] = &[ADM_USERS, ADM_ROLES, ADM_PERMISSIONS, CFG_MANAGE, CFG_PUBLISH, ERP_CONFIGURE, LOG_EXPORT, CONSOLE_VIEW, CUSTOMER_MANAGE, ENTITLEMENT_MANAGE, SYNC_OPERATE, ROLLOUT_MANAGE, PLATFORM_OBSERVE, AUDIT_VIEW, LIC_MANAGE, ENT_MANAGE, ACT_MANAGE];

/// Default Operator / Maintenance Technician permission set.
pub const OPERATOR_PERMISSIONS: &[&str] = &[EQ_VIEW, EQ_MANAGE, DI_VIEW, DI_CREATE, DI_CREATE_OWN, OT_VIEW, OT_CREATE, OT_EDIT, OT_CLOSE, ORG_VIEW, PER_VIEW, PER_REPORT, REF_VIEW, INV_VIEW, INV_MANAGE, PM_VIEW, RAM_VIEW, SYNC_VIEW, REP_VIEW, ARC_VIEW, DOC_VIEW, PLAN_VIEW, LOG_VIEW, TRN_VIEW, IOT_VIEW, ERP_VIEW, PTW_VIEW, PTW_ISSUE, FIN_VIEW, FIN_REPORT, INS_VIEW, INS_EXECUTE, CFG_VIEW];

/// Default Planner/Scheduler permission set.
pub const PLANNER_PERMISSIONS: &[&str] = &[OT_VIEW, OT_CREATE, OT_EDIT, DI_VIEW, DI_CREATE, DI_SCREEN, PM_VIEW, PM_CREATE, PM_EDIT, PM_APPROVE, PLAN_VIEW, PLAN_EDIT, PLAN_CONFIRM, PLAN_WINDOWS, EQ_VIEW, INV_VIEW, INV_MANAGE, INV_PROCURE, ORG_VIEW, PER_VIEW, PER_REPORT, REF_VIEW, REP_VIEW, REP_EXPORT, ARC_VIEW, DOC_VIEW, LOG_VIEW, RAM_VIEW, SYNC_VIEW, CFG_VIEW];

/// Resolve a permission or alias to its canonical name.
pub fn canonicalize(name: &str) -> Option<&'static str> {
    for meta in CATALOG {
        if meta.name == name {
            return Some(meta.name);
        }
        if meta.aliases.iter().any(|a| *a == name) {
            return Some(meta.name);
        }
    }
    None
}

/// All canonical permission names.
pub fn all_names() -> impl Iterator<Item = &'static str> {
    CATALOG.iter().map(|m| m.name)
}

