#!/usr/bin/env tsx
/**
 * generate-permissions.ts
 *
 * Reads shared/rbac/permission-registry.json (the only place permission-name
 * strings may be authored) and writes:
 *   - src-tauri/src/rbac/permissions_generated.rs
 *   - shared/rbac/permissions.generated.ts
 *
 * Deterministic output. Checked into source control.
 *
 * Usage:
 *   pnpm rbac:generate
 *   pnpm rbac:check   (via check-rbac-parity.ts --check-generated)
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const REGISTRY_PATH = path.join(ROOT, "shared/rbac/permission-registry.json");
const RUST_OUT = path.join(ROOT, "src-tauri/src/rbac/permissions_generated.rs");
const TS_OUT = path.join(ROOT, "shared/rbac/permissions.generated.ts");

interface PermissionEntry {
  name: string;
  description: string;
  category: string;
  is_dangerous: boolean;
  requires_step_up: boolean;
  usage: "backend" | "frontend" | "both" | "catalog-only";
  usage_justification?: string;
  aliases: string[];
}

interface DependencyEntry {
  permission: string;
  requires: string;
  dep_type: "hard" | "warn";
}

interface Registry {
  version: number;
  permissions: PermissionEntry[];
  dependencies: DependencyEntry[];
  role_defaults: {
    supervisor_exclusions: string[];
    operator: string[];
    planner: string[];
  };
  role_templates: Record<string, string[]>;
}

function constName(permissionName: string): string {
  return permissionName.replace(/\./g, "_").toUpperCase();
}

function loadRegistry(): Registry {
  const raw = fs.readFileSync(REGISTRY_PATH, "utf-8");
  const registry = JSON.parse(raw) as Registry;
  if (!Array.isArray(registry.permissions) || registry.permissions.length === 0) {
    throw new Error("permission-registry.json has no permissions");
  }
  const names = new Set<string>();
  for (const p of registry.permissions) {
    if (names.has(p.name)) {
      throw new Error(`Duplicate permission: ${p.name}`);
    }
    names.add(p.name);
    if (p.usage === "catalog-only" && !p.usage_justification?.trim()) {
      throw new Error(`catalog-only permission ${p.name} requires usage_justification`);
    }
  }
  for (const dep of registry.dependencies) {
    if (!names.has(dep.permission) || !names.has(dep.requires)) {
      throw new Error(
        `Dependency references unknown permission: ${dep.permission} -> ${dep.requires}`,
      );
    }
  }
  return registry;
}

function generateRust(registry: Registry): string {
  const lines: string[] = [];
  lines.push("// @generated by scripts/generate-permissions.ts — DO NOT EDIT");
  lines.push("// Source: shared/rbac/permission-registry.json");
  lines.push("");
  lines.push("#![allow(dead_code)]");
  lines.push("");
  lines.push("//! Generated canonical permission constants and catalog metadata.");
  lines.push("");
  lines.push("/// One row from the canonical permission registry.");
  lines.push("#[derive(Debug, Clone, Copy)]");
  lines.push("pub struct PermissionMeta {");
  lines.push("    pub name: &'static str,");
  lines.push("    pub description: &'static str,");
  lines.push("    pub category: &'static str,");
  lines.push("    pub is_dangerous: bool,");
  lines.push("    pub requires_step_up: bool,");
  lines.push("    pub usage: &'static str,");
  lines.push("    pub aliases: &'static [&'static str],");
  lines.push("}");
  lines.push("");
  lines.push("/// Dependency edge from the canonical registry.");
  lines.push("#[derive(Debug, Clone, Copy)]");
  lines.push("pub struct PermissionDep {");
  lines.push("    pub permission: &'static str,");
  lines.push("    pub requires: &'static str,");
  lines.push("    pub dep_type: &'static str,");
  lines.push("}");
  lines.push("");

  for (const p of registry.permissions) {
    const c = constName(p.name);
    lines.push(`/// ${p.description}`);
    lines.push(`pub const ${c}: &str = "${p.name}";`);
  }
  lines.push("");

  lines.push("/// Full canonical catalog (system permissions).");
  lines.push("pub const CATALOG: &[PermissionMeta] = &[");
  for (const p of registry.permissions) {
    const aliasLit =
      p.aliases.length === 0 ? "&[]" : `&[${p.aliases.map((a) => `"${a}"`).join(", ")}]`;
    lines.push("    PermissionMeta {");
    lines.push(`        name: ${constName(p.name)},`);
    lines.push(`        description: ${JSON.stringify(p.description)},`);
    lines.push(`        category: ${JSON.stringify(p.category)},`);
    lines.push(`        is_dangerous: ${p.is_dangerous},`);
    lines.push(`        requires_step_up: ${p.requires_step_up},`);
    lines.push(`        usage: ${JSON.stringify(p.usage)},`);
    lines.push(`        aliases: ${aliasLit},`);
    lines.push("    },");
  }
  lines.push("];");
  lines.push("");

  lines.push("/// Canonical permission dependencies.");
  lines.push("pub const DEPENDENCIES: &[PermissionDep] = &[");
  for (const d of registry.dependencies) {
    lines.push("    PermissionDep {");
    lines.push(`        permission: ${constName(d.permission)},`);
    lines.push(`        requires: ${constName(d.requires)},`);
    lines.push(`        dep_type: ${JSON.stringify(d.dep_type)},`);
    lines.push("    },");
  }
  lines.push("];");
  lines.push("");

  lines.push("/// Alias → canonical name pairs for grant migration.");
  lines.push("pub const ALIAS_MAP: &[(&str, &str)] = &[");
  for (const p of registry.permissions) {
    for (const alias of p.aliases) {
      lines.push(`    ("${alias}", ${constName(p.name)}),`);
    }
  }
  lines.push("];");
  lines.push("");

  const excl = registry.role_defaults.supervisor_exclusions;
  lines.push("/// Permissions excluded from Supervisor / Maintenance Supervisor defaults.");
  lines.push(
    `pub const SUPERVISOR_EXCLUSIONS: &[&str] = &[${excl.map((n) => constName(n)).join(", ")}];`,
  );
  lines.push("");

  const op = registry.role_defaults.operator;
  lines.push("/// Default Operator / Maintenance Technician permission set.");
  lines.push(
    `pub const OPERATOR_PERMISSIONS: &[&str] = &[${op.map((n) => constName(n)).join(", ")}];`,
  );
  lines.push("");

  const pl = registry.role_defaults.planner;
  lines.push("/// Default Planner/Scheduler permission set.");
  lines.push(
    `pub const PLANNER_PERMISSIONS: &[&str] = &[${pl.map((n) => constName(n)).join(", ")}];`,
  );
  lines.push("");

  lines.push("/// Resolve a permission or alias to its canonical name.");
  lines.push("pub fn canonicalize(name: &str) -> Option<&'static str> {");
  lines.push("    for meta in CATALOG {");
  lines.push("        if meta.name == name {");
  lines.push("            return Some(meta.name);");
  lines.push("        }");
  lines.push("        if meta.aliases.iter().any(|a| *a == name) {");
  lines.push("            return Some(meta.name);");
  lines.push("        }");
  lines.push("    }");
  lines.push("    None");
  lines.push("}");
  lines.push("");
  lines.push("/// All canonical permission names.");
  lines.push("pub fn all_names() -> impl Iterator<Item = &'static str> {");
  lines.push("    CATALOG.iter().map(|m| m.name)");
  lines.push("}");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function generateTs(registry: Registry): string {
  const lines: string[] = [];
  lines.push("// @generated by scripts/generate-permissions.ts — DO NOT EDIT");
  lines.push("// Source: shared/rbac/permission-registry.json");
  lines.push("");
  lines.push("/** Canonical permission name constants. Use these instead of string literals. */");
  lines.push("export const P = {");
  for (const p of registry.permissions) {
    lines.push(`  ${constName(p.name)}: "${p.name}",`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type PermissionName = (typeof P)[keyof typeof P];");
  lines.push("");
  lines.push('export type PermissionUsage = "backend" | "frontend" | "both" | "catalog-only";');
  lines.push("");
  lines.push("export interface PermissionMeta {");
  lines.push("  name: PermissionName;");
  lines.push("  description: string;");
  lines.push("  category: string;");
  lines.push("  isDangerous: boolean;");
  lines.push("  requiresStepUp: boolean;");
  lines.push("  usage: PermissionUsage;");
  lines.push("  usageJustification?: string;");
  lines.push("  aliases: readonly string[];");
  lines.push("}");
  lines.push("");
  lines.push("export const PERMISSION_CATALOG: readonly PermissionMeta[] = [");
  for (const p of registry.permissions) {
    lines.push("  {");
    lines.push(`    name: P.${constName(p.name)},`);
    lines.push(`    description: ${JSON.stringify(p.description)},`);
    lines.push(`    category: ${JSON.stringify(p.category)},`);
    lines.push(`    isDangerous: ${p.is_dangerous},`);
    lines.push(`    requiresStepUp: ${p.requires_step_up},`);
    lines.push(`    usage: ${JSON.stringify(p.usage)},`);
    if (p.usage_justification) {
      lines.push(`    usageJustification: ${JSON.stringify(p.usage_justification)},`);
    }
    lines.push(`    aliases: [${p.aliases.map((a) => JSON.stringify(a)).join(", ")}] as const,`);
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");
  lines.push("export const PERMISSION_NAME_SET: ReadonlySet<string> = new Set(");
  lines.push("  PERMISSION_CATALOG.map((p) => p.name),");
  lines.push(");");
  lines.push("");
  lines.push("export function isPermissionName(value: string): value is PermissionName {");
  lines.push("  return PERMISSION_NAME_SET.has(value);");
  lines.push("}");
  lines.push("");
  lines.push("/** Alias → canonical map for migration / display. */");
  lines.push("export const PERMISSION_ALIAS_MAP: Readonly<Record<string, PermissionName>> = {");
  for (const p of registry.permissions) {
    for (const alias of p.aliases) {
      lines.push(`  ${JSON.stringify(alias)}: P.${constName(p.name)},`);
    }
  }
  lines.push("};");
  lines.push("");
  lines.push(
    "export const ROLE_TEMPLATES: Readonly<Record<string, readonly PermissionName[]>> = {",
  );
  for (const [name, perms] of Object.entries(registry.role_templates)) {
    lines.push(`  ${JSON.stringify(name)}: [${perms.map((n) => `P.${constName(n)}`).join(", ")}],`);
  }
  lines.push("};");
  lines.push("");
  return `${lines.join("\n")}\n`;
}

function main(): void {
  const registry = loadRegistry();
  const rust = generateRust(registry);
  const ts = generateTs(registry);
  fs.mkdirSync(path.dirname(RUST_OUT), { recursive: true });
  fs.mkdirSync(path.dirname(TS_OUT), { recursive: true });
  fs.writeFileSync(RUST_OUT, rust, "utf-8");
  fs.writeFileSync(TS_OUT, ts, "utf-8");
  console.log(
    `Wrote ${path.relative(ROOT, RUST_OUT)} (${registry.permissions.length} permissions)`,
  );
  console.log(`Wrote ${path.relative(ROOT, TS_OUT)}`);
}

main();
