/**
 * AssetQrCode.tsx
 *
 * QR code popover for asset identification. Encodes maintafox://asset/{id}.
 * Features: SVG display, PNG download, print layout.
 */

import { Download, Printer, QrCode } from "lucide-react";
import QRCode from "qrcode";
import { useCallback, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";

import { PermissionGate } from "@/components/PermissionGate";
import { Button } from "@/components/ui/button";
import type { Asset } from "@shared/ipc-types";

interface AssetQrCodeProps {
  asset: Asset;
}

const QR_SIZE = 200;

export function AssetQrCode({ asset }: AssetQrCodeProps) {
  const { t } = useTranslation("equipment");
  const [open, setOpen] = useState(false);
  const [svgHtml, setSvgHtml] = useState("");
  const popoverRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const uri = `maintafox://asset/${asset.id}`;

  // Generate QR SVG
  useEffect(() => {
    if (open) {
      void QRCode.toString(uri, {
        type: "svg",
        width: QR_SIZE,
        margin: 1,
      }).then(setSvgHtml);
    }
  }, [open, uri]);

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (popoverRef.current && !popoverRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  // Download as PNG
  const handleDownload = useCallback(async () => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    await QRCode.toCanvas(canvas, uri, {
      width: QR_SIZE * 2,
      margin: 2,
    });

    const link = document.createElement("a");
    link.download = `${asset.asset_code}-qr.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  }, [uri, asset.asset_code]);

  // Print
  const handlePrint = useCallback(() => {
    const printWindow = window.open("", "_blank", "width=400,height=500");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>QR — ${asset.asset_code}</title>
        <style>
          body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            margin: 0;
            font-family: system-ui, sans-serif;
          }
          .code { font-size: 18px; font-weight: 700; font-family: monospace; margin-top: 16px; }
          .name { font-size: 14px; color: #555; margin-top: 4px; }
          @media print {
            body { padding: 20mm; }
          }
        </style>
      </head>
      <body>
        ${svgHtml}
        <div class="code">${asset.asset_code}</div>
        <div class="name">${asset.asset_name}</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  }, [svgHtml, asset.asset_code, asset.asset_name]);

  return (
    <PermissionGate permission="eq.view">
      <div className="relative inline-block">
        <Button variant="outline" size="sm" className="gap-1.5" onClick={() => setOpen(!open)}>
          <QrCode className="h-3.5 w-3.5" />
          {t("qr.button")}
        </Button>

        {open && (
          <div
            ref={popoverRef}
            className="absolute right-0 top-full mt-2 z-50 w-[260px] rounded-lg border border-surface-border bg-surface p-4 shadow-lg"
          >
            {/* QR SVG */}
            <div
              className="flex justify-center"
              // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG generated by qrcode lib
              dangerouslySetInnerHTML={{ __html: svgHtml }}
            />

            {/* Asset info */}
            <div className="mt-3 text-center">
              <p className="font-mono text-sm font-bold">{asset.asset_code}</p>
              <p className="text-xs text-text-muted">{asset.asset_name}</p>
            </div>

            {/* Actions */}
            <div className="mt-3 flex gap-2 justify-center">
              <Button
                variant="outline"
                size="sm"
                className="gap-1 text-xs"
                onClick={() => void handleDownload()}
              >
                <Download className="h-3 w-3" />
                {t("qr.download")}
              </Button>
              <Button variant="outline" size="sm" className="gap-1 text-xs" onClick={handlePrint}>
                <Printer className="h-3 w-3" />
                {t("qr.print")}
              </Button>
            </div>

            {/* Hidden canvas for PNG export */}
            <canvas ref={canvasRef} className="hidden" />
          </div>
        )}
      </div>
    </PermissionGate>
  );
}
